name: Publish 8.0 Apache
on:
    workflow_run: 
     workflows: ["Publish Polyscripting Tools"]
     types:
      - completed
    push:
     paths:
      - '8.0/buster/apache/**'
      - '.github/workflows/8.0-apache-publish.yml'
jobs:
    build:
      if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}            
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: ./publish-image.sh
        working-directory: ./8.0/buster/apache/
      - name: Run Test Suite
        run: ./workflow-test.sh
        working-directory: ./polyscripting/tools/test/
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_POLYSCRIPTING_SECRET }}
      - name: Publish 8.0 Apache Git Package Repository
        run: ./publish-image.sh -g
        shell: bash
        working-directory: ./8.0/buster/apache/
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish 8.0 Apache Docker Hub
        run: ./publish-image.sh -p
        shell: bash
        working-directory: ./8.0/buster/apache/
      - name: Trigger Downstream
        run: |
             curl -X POST https://api.github.com/repos/polyverse/polyscripted-wordpress/dispatches \
             -H 'Accept: application/vnd.github.everest-preview+json' \
             -u ${{ secrets.GHCR_POLYSCRIPTING_SECRET }}  \
             --data '{"event_type" : "build_8.0_apache", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
        
