name: Publish 8.4 Apache
on:
    workflow_run: 
     workflows: ["Publish Encrypted Execution Tools"]
     types:
      - completed
    push:
      branches:
        - main
      paths:
      - '8.4/bookworm/apache/**'
      - '.github/workflows/8.4-apache-publish.yml'
jobs:
    build:
      if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}            
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: ./publish-image.sh
        working-directory: ./8.4/bookworm/apache/
      - name: Run Test Suite
        run: ./workflow-test.sh
        working-directory: ./encrypted-execution/tools/test/
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PUBLISH_PERSONAL_ACCESS_TOKEN }}
      - name: Publish 8.4 Apache Git Package Repository
        run: ./publish-image.sh -g
        shell: bash
        working-directory: ./8.4/bookworm/apache/
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish 8.4 Apache Docker Hub
        run: ./publish-image.sh -p
        shell: bash
        working-directory: ./8.4/bookworm/apache/
      - name: Trigger Downstream
        run: |
             curl \
             -X POST \
             -H 'Accept: application/vnd.github.v3+json' \
             https://api.github.com/repos/encrypted-execution/encrypted-execution-wordpress/dispatches \
             -d '{"event_type" : "build_8.4_apache", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
        
