name: Publish all php docker images 
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: azure/docker-login@v1
          with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Publish All
          run: echo $PATH
          shell: bash
          working-directory: ./polyscripting/tools
