name: Publish all php docker images 
on: [push]
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build Php
        run: docker build -t test .
        shell: bash
        working-directory: ./7.2/stretch/fpm/
